apiVersion: apps/v1
kind: Deployment
metadata:
  name: convtemp
spec:
  selector:
    matchLabels:
      app: convtemp
  template:
    metadata:
      labels:
        app: convtemp
    spec:
      containers:
      - name: convtemp
        image: gabrielalegra\conv-temp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: convtemp
spec:
  selector:
    app: convtemp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort